[package]
name = "dioxus-js-interop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Zero-build, low-annotation, RAII-safe JS/TS FFI and InteropRuntime engine for Dioxus"
readme = "../../README.md"

[dependencies]
dioxus-js-interop-macro = { path = "../dioxus-js-interop-macro", version = "0.1.2" }

dioxus.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
