[package]
name = "oxidase"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "High-performance browser FFI runtime engine for Dioxus"
readme = "../../README.md"

[dependencies]
oxidase-macro = { path = "../oxidase-macro", version = "0.1.2" }

dioxus.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
